# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20161017_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 17, 16, 58, 57, 760990), null=True),
        ),
    ]
