# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20161017_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 18, 7, 12, 57, 349930), null=True),
        ),
    ]
